### ISSUE TITLE
Feature - cronjob max complete/failed pods history limits

### ISSUE THREAD

**Issue by gerardgorrion** [ryaneorth/scheduled-volume-snapshotter#1]
We are interesing to use this application using helm deploy, but we don't want to conserve cronjobs pods history, managed into cronjob in yaml file:
```
...
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
...
```
Is possible to add to values yaml file this attribute?

regards

**Comment by ryaneorth** [comment]
Hi @gerardgorrion - I can look at adding that as an option. I may not get to it for a few days, but I'll commenr back on this issue once it is implemented

**Comment by ryaneorth** [comment]
This functionality has been added and is in the [v0.6.0 release](https://github.com/ryaneorth/scheduled-volume-snapshotter/releases/tag/v0.6.0)
